### ISSUE TITLE
你好，不知道现在的签名算法有更新吗

### ISSUE THREAD

**Issue by sanbap6537** [AppSign/douyin#1]
你好，之前我用您的接口测试了一下签名算法，我现在找不到ios2.0.0的抖音，所以测试没成功，不知道您哪有没有

**Comment by AppSign** [comment]
目前签名算法支持2.0.0 - 2.6.0(最新版本)，实际测试成功。
从最新版本APP中抓到的数据包可以直接使用

**Comment by sanbap6537** [comment]
你好，方不方便价格qq，我的qq是573081351





在 2018-09-13 00:50:37，"AppSign" <notifications@github.com> 写道：


目前签名算法支持2.0.0 - 2.6.0(最新版本)，实际测试成功。
从最新版本APP中抓到的数据包可以直接使用

**Comment by AppSign** [comment]
如果2.6.0提示2151签名失败的情况下，可以使用2.0.0 appinfo，使用2.6.0抓下来的包，大部分2.0.0重放也是可以使用的
之后会更新最新版本的协议

**Comment by fengzhengkeji** [comment]
注册这块用您的代码测试了一下，使用2.0.0的话会报“版本过低”，使用2.6.0的话会报“访问太频繁”。不知这里有什么需要注意的。

**Comment by AppSign** [comment]
注册这块2.0.0不允许注册了， 我之前测试注册使用的是2.5.1版本的，你可以试试2.5.1
最新的2.6.0当前api支持的不好，之后有时间会更新协议版本。

**Comment by fengzhengkeji** [comment]
> 注册这块2.0.0不允许注册了， 我之前测试注册使用的是2.5.1版本的，你可以试试2.5.1
> 最新的2.6.0当前api支持的不好，之后有时间会更新协议版本。

嗯嗯，重新测试了一遍可以了。我现在尝试自己抓包想参照您的代码试着写下还没上传的几个功能模块，但是好像iOS系统不越狱无法抓包，不知道你是怎么解决这个问题的。通过安卓抓包的参数和iOS的不一样应该不能用。

**Comment by fengzhengkeji** [comment]
> iOS可以抓包的，你可以百度搜索下，挂上代理，安装证书，就可以抓包。
> 
> 写了代码欢迎提交pull

嗯，今天刚解决iOS11以上系统抓包无网络的问题，原来更新iOS11.0以上之后，下载证书只是安装没有信任，抓包的话证书需要在设置里修改成信任。
还有今天测试代码的时候api.appsign.vip接口好像无法请求了，不知道是否是宕机了。
方便加下微信吗，我的是13151692119，非常感谢您的分享，希望能多多交流请教。
