### ISSUE TITLE
短信登陆，发送验证码失败

### ISSUE THREAD

**Issue by KlarY** [AppSign/douyin#11]
RT

**Comment by KlarY** [comment]
只填写了手机号，不知道是不是要更改别的参数，一直报发送验证码失败

**Comment by qiuhuo** [comment]
发送失败是需要验证码，返回1104是点选验证，1105是滑块验证

**Comment by KlarY** [comment]
好的谢谢，那如果解决或者绕过呢？还有个问题是QQ登陆验证的post_params是要自己手动抓包的嘛？

**Comment by AppSign** [comment]
手机发送验证码，发送失败看返回值 可能需要验证码

QQ登陆验证的post_params需要自己手动抓包

**Comment by liupengpo** [comment]
> 1104



> 发送失败是需要验证码，返回1104是点选验证，1105是滑块验证

我的返回的是1104，怎么处理呢？
