### ISSUE TITLE
It is not working anymore

### ISSUE THREAD

**Issue by AlexTerry1024** [AppSign/douyin#14]
Sign str: os_api=18&app_version=2.7.0&os_version=11.0&ac=WIFI&channel=App%20Stroe&version_code=2.7.0&aid=1128&screen_width=750&iid=46971166879&device_id=58377573299&type=3731&mix_mode=1&vid=E9ED95E7-FFAE-78C0-EF91-6BC16EE6BC23&device_type=iPhone8,1&mobile=2e3d333436343731373033353130&openudid=d48a0bdcee66a177f16fb3bdf73acbcb536fbeac&build_number=27014&idfa=ECBC00FF-B6FE-DF44-DBDD-91C9DDC92BA0&device_platform=iphone&app_name=aweme
{'os_api': '18', 'ac': 'WIFI', 'channel': 'App%20Stroe', 'version_code': '2.7.0', 'screen_width': '750', 'iid': 46971166879, 'type': '3731', 'mix_mode': '1', 'device_type': 'iPhone8,1', 'openudid': 'd48a0bdcee66a177f16fb3bdf73acbcb536fbeac', 'mobile': '2e3d333436343731373033353130', 'build_number': '27014', 'idfa': 'ECBC00FF-B6FE-DF44-DBDD-91C9DDC92BA0', 'app_name': 'aweme', 'as': 'a125d36cd9d18b644d8625', 'app_version': '2.7.0', 'aid': '1128', 'mas': '01ec756fb00313af0cd8f43c12f1b8422f9f8fed9630afb3ca6a9e', 'device_id': 58377573299, 'vid': 'E9ED95E7-FFAE-78C0-EF91-6BC16EE6BC23', 'device_platform': 'iphone', 'ts': '1540174873', 'os_version': '11.0'}
{'data': {'description': '', 'error_code': 1104, 'captcha': ''}, 'message': 'error'}

**Comment by AppSign** [comment]
You can try to capture the app package and then analyze it

**Comment by AppSign** [comment]
1
