### ISSUE TITLE
你好，search貌似使用不了

### ISSUE THREAD

**Issue by aReu4mE** [AppSign/douyin#22]
前两天还能正常使用搜索功能，但是今天就不行了

**Comment by najsword** [comment]
me too,  By catching packges by fiddler  and analysing interfaces ，the results show like this:
ALL new Params:
cursor=0&
keyword=shiyy999&
count=10&
type=1&
is_pull_refresh=0&
hot_search=0&
ts=1542189571     
js_sdk_version=1.2.2&
app_type=normal&
os_api=23&
device_type=MuMu&
device_platform=android&
ssmix=a&
iid=50124592661&
manifest_version_code=310&
dpi=270&
uuid=008796762142351&
version_code=310&
app_name=aweme&
version_name=3.1.0&
openudid=5c1dc039ad5481c6&
device_id=59040142349&
resolution=810*1440&
os_version=6.0.1&
language=zh&
device_brand=Android&
ac=wifi&
update_version_code=3102&
aid=1128&
channel=wandoujia_zhiwei&
_rticket=1542189651310&

as=a1659f7eb360fb02cb6455&
cp=f201bd553eb8e425e1Si%5Bm&
mas=01acb8e332c537a8d8a060a14d190e51e5acac2c6c46c64c0c4666


new  param( compare old version)
ssmix  cursor  type  is_pull_refresh  hot_search  uuid
js_sdk_version  app_type  ssmix   manifest_version_code   dpi
version_name   resolution  language  device_brand  update_version_code
_rticket  cp  

delete param ( compare old version)
idfa  vid  screen_width  build_number  app_version  offset

**Comment by AppSign** [comment]
新生成的设备信息无法直接使用搜索，需要使用历史设备信息就可以进行搜索

**Comment by yeyicheng** [comment]
请问怎么使用历史设备？
