### ISSUE TITLE
可以采集点赞，评论、分享数等功能了吗？

### ISSUE THREAD

**Issue by buptbf** [AppSign/douyin#23]
_Originally posted by @AppSign in https://github.com/AppSign/douyin/issues/16#issuecomment-433674434_

**Comment by 1ookup** [comment]
获取视频点赞评论，分享数量可以参考videoInfo.py这个文件，里面已经写的明明白白白的。
```
print("forward_count: ", resp['aweme_detail']['statistics']['forward_count'])
print("digg_count: ", resp['aweme_detail']['statistics']['digg_count'])
print("comment_count: ", resp['aweme_detail']['statistics']['comment_count'])
print("share_count: ", resp['aweme_detail']['statistics']['share_count'])
```

**Comment by AppSign** [comment]
点赞，分享，评论可以参考`videoInfo.py`文件
```
print("forward_count: ", resp['aweme_detail']['statistics']['forward_count'])
print("digg_count: ", resp['aweme_detail']['statistics']['digg_count'])
print("comment_count: ", resp['aweme_detail']['statistics']['comment_count'])
print("share_count: ", resp['aweme_detail']['statistics']['share_count'])
```

**Comment by buptbf** [comment]
感谢大神。请问videoInfo.py中输出的 duration属性是指什么呀？总的播放时间吗？
('author: ', u'\u4eba\u6c11\u65e5\u62a5')
('forward_count: ', 558)
('digg_count: ', 231582)
('comment_count: ', 7106)
('share_count: ', 5777)
('music: ', u'@\u4eba\u6c11\u65e5\u62a5\u521b\u4f5c\u7684\u539f\u58f0')
('covers: ', [u'http://p9-dy.bytecdn.cn/large/c7490001f54697596da7.jpeg', u'http://p1-dy.bytecdn.cn/large/c7490001f54697596da7.jpeg', u'http://pb3.pstatp.com/large/c7490001f54697596da7.jpeg'])
('dynamic_cover: ', [u'https://p1-dy.bytecdn.cn/obj/c70000065af247d142f5', u'https://p3-dy.bytecdn.cn/obj/c70000065af247d142f5', u'https://pb3.pstatp.com/obj/c70000065af247d142f5'])
('duration: ', 33570)
