### ISSUE TITLE
https://api.appsign.vip 不能访问

### ISSUE THREAD

**Issue by ttc9082** [AppSign/douyin#3]
你好，请问这个服务稳定吗？能提供一些相关信息吗？十分感谢。

**Comment by AppSign** [comment]
之前访问量太大了，内存满了，服务宕了，昨天优化了下代码，不会再出现内存跑满情况，目前比较稳定
毕竟提供免费服务，服务器配置成本不会投入太多，但是会保障最基本的稳定访问

如果还有什么使用方面的问题也可以提问，有时间就会解答

**Comment by ttc9082** [comment]
方便加一下微信吗 ttc9082，免费提供服务确实很不容易，很感谢你这个项目我也希望能够做出一些贡献。

**Comment by AppSign** [comment]
****毅

**Comment by liuyaming123** [comment]
接口又不能访问了
